### ISSUE TITLE
Windows: upload plugin does not create folder on target drive

### ISSUE THREAD

**Issue by zoubirnouicer** [mirokolodii/android-files-uploader-plugin#3]
The function private fun String.splitToNestedFolders() = split("/").filter { it.isNotBlank() } is not OS agnostic.
We can try this: private fun String.splitToNestedFolders() = split(File.separator).filter { it.isNotBlank() }

**Comment by mirokolodii** [comment]
Thanks for suggestion @zoubirnouicer. Fixed https://github.com/mirokolodii/android-files-uploader-plugin/pull/5.
